import type { ActivityLog, ProfileLink, Report, UserProfile } from "./types";

// FUTURO SUPABASE: este seed some quando as tabelas reais existirem.

const now = Date.now();
const iso = (daysAgo: number) => new Date(now - daysAgo * 86400000).toISOString();

export const SEED_USERS: UserProfile[] = [
  {
    id: "u_admin",
    email: "admin@nabio.app",
    username: "admin",
    displayName: "Equipe Na Bio",
    bio: "Administração da plataforma",
    themeId: "neon-dark",
    plan: "pro",
    status: "active",
    role: "admin",
    featuredOnHome: false,
    featuredOrder: 0,
    pageViews: 0,
    createdAt: iso(120),
  },
  {
    id: "u_edu",
    email: "edu@nabio.app",
    username: "oedubernard",
    displayName: "Edu Bernard",
    bio: "Criador de conteúdo • São Paulo",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=60",
    backgroundUrl:
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=60",
    counterLabel: "seguidores",
    counterValue: "1.8M",
    themeId: "dark-elegant",
    plan: "pro",
    status: "active",
    role: "user",
    featuredOnHome: false,
    featuredOrder: 0,
    pageViews: 18420,
    createdAt: iso(45),
  },
  {
    id: "u_lari",
    email: "lari@nabio.app",
    username: "larissamakes",
    displayName: "Larissa Makeup",
    bio: "Maquiadora profissional",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=60",
    counterLabel: "clientes atendidas",
    counterValue: "2.4k",
    themeId: "vibrant-gradient",
    plan: "free",
    status: "active",
    role: "user",
    featuredOnHome: false,
    featuredOrder: 0,
    pageViews: 3120,
    createdAt: iso(18),
  },
  {
    id: "u_studio",
    email: "studio@nabio.app",
    username: "studiotatu",
    displayName: "Studio Tatu",
    bio: "Tattoo & piercing",
    themeId: "light-minimal",
    plan: "free",
    status: "suspended",
    role: "user",
    featuredOnHome: false,
    featuredOrder: 0,
    pageViews: 890,
    createdAt: iso(7),
  },
];

export const SEED_LINKS: ProfileLink[] = [
  {
    id: "l1",
    userId: "u_edu",
    title: "Meu novo single",
    type: "youtube",
    value: "https://youtube.com/@oedubernard",
    thumbnail:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=120&q=60",
    position: 0,
    active: true,
    clicks: 4210,
    createdAt: iso(30),
  },
  {
    id: "l2",
    userId: "u_edu",
    title: "Fale comigo no WhatsApp",
    type: "whatsapp",
    value: "5511999998888",
    position: 1,
    active: true,
    clicks: 2870,
    createdAt: iso(28),
  },
  {
    id: "l3",
    userId: "u_edu",
    title: "Instagram",
    type: "instagram",
    value: "https://instagram.com/oedubernard",
    position: 2,
    active: true,
    clicks: 5310,
    createdAt: iso(27),
  },
  {
    id: "l4",
    userId: "u_edu",
    title: "Apoie com PIX",
    type: "pix",
    value: "edu@nabio.app",
    position: 3,
    active: true,
    clicks: 640,
    createdAt: iso(12),
  },
  {
    id: "l5",
    userId: "u_edu",
    title: "Press kit (PDF)",
    type: "file",
    value: "https://example.com/presskit.pdf",
    position: 4,
    active: false,
    clicks: 120,
    createdAt: iso(9),
  },
  {
    id: "l6",
    userId: "u_lari",
    title: "Agendar horário",
    type: "whatsapp",
    value: "5511977776666",
    position: 0,
    active: true,
    clicks: 980,
    createdAt: iso(15),
  },
  {
    id: "l7",
    userId: "u_lari",
    title: "Portfólio no Instagram",
    type: "instagram",
    value: "https://instagram.com/larissamakes",
    position: 1,
    active: true,
    clicks: 1240,
    createdAt: iso(14),
  },
  {
    id: "l8",
    userId: "u_studio",
    title: "Nosso site",
    type: "url",
    value: "https://studiotatu.com.br",
    position: 0,
    active: true,
    clicks: 210,
    createdAt: iso(6),
  },
];

export const SEED_REPORTS: Report[] = [
  {
    id: "r1",
    reportedUserId: "u_studio",
    reason: "Conteúdo impróprio na imagem de fundo",
    reporter: "@anonimo",
    createdAt: iso(3),
    resolved: false,
  },
  {
    id: "r2",
    reportedUserId: "u_lari",
    reason: "Link suspeito de golpe",
    reporter: "@joaosilva",
    createdAt: iso(1),
    resolved: false,
  },
];

export const SEED_LOGS: ActivityLog[] = [
  { id: "a1", type: "signup", message: "Novo cadastro: @studiotatu", createdAt: iso(7) },
  { id: "a2", type: "suspend", message: "@studiotatu suspenso por denúncia", createdAt: iso(2) },
  { id: "a3", type: "link", message: "@oedubernard adicionou um link PIX", createdAt: iso(12) },
];
